apiVersion: v1
kind: RoleBindingRestriction
metadata:
  name: match-groups
spec:
  ggrouprestriction:
    groups: ["groups-rolebindingrestriction"]
  userrestriction: null
  serviceaccountrestriction: null
  grouprestriction: null
