apiVersion: v1
kind: RoleBindingRestriction
metadata:
  name: match-groups
spec:
  ggrouprestriction:
    groups: ["groups-rolebindingrestriction"]
    serviceaccounts:
    - name: service_account_name1
      namespace: namespace1 2
  userrestriction: null
  grouprestriction: null
