apiVersion: v1
kind: RoleBindingRestriction
metadata:
  name: match-groups
spec:
  grouprestriction:
    groups: ["groups-rolebindingrestriction"]
    labels: null
  userrestriction: null
  serviceaccountrestriction: null
